app:
  id: "48613de843efd" # replace with random string

  dev: true

  directory:
    root: "%root%"
    public: "%root%"
    pages: "%root%/pages"

  endpoints:
    home: "home:index"
    auth:
      login: "auth:login"
      logout: "auth:logout"

  database:
    database: "poo_hello_world"
    host: "localhost"
    user: "app"
    password: "app"
    port: 3306
    connect_database: false

  cookie:
    first_connection: "fc"
